//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.24 at 12:26:41 PM BDT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://madbarsoft.com/students", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.madbarsoft.students;
