server:
  port: 8282




resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
    getMsgConfig:
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 120s
      automaticTransitionFromOpenToHalfOpenEnabled: true
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
  instances:
    getMsg:
      baseConfig: getMsgConfig
      
      
      
#
#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        registerHealthIndicator: true
#        failureRateThreshold: 70
#        minimumNumberOfCalls: 8
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        waitDurationInOpenState: 60s
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowType: COUNT_BASED


#ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  health.circuitbreakers.enabled: true
  
  
  
  
  