
# ===============================
# = Server Properties
# ===============================
server:
  port: 8181
spring:
  application:
    name: redis-sentinel-cluster
  redis:
    port: 26379
    password: BLOpenApi@2021_$
    sentinel:
      master: mymaster
      nodes:
        - 172.16.7.161
        - 172.16.8.250
        - 172.16.8.251
    lettuce:
      shutdown-timeout: 1000ms  


cache-config:
  defaultConfigs:
  -  cacheName: CACHE4_ONE_DAY       
     timeToLiveSeconds: 86400
  -  cacheName: CACHE4_SAVEN_DAY
     timeToLiveSeconds: 604800

api-mapping:
  appCacheMap:
    'redis-sentinel-cluster:get-info': CACHE4_ONE_DAY
    'redis-sentinel-cluster:get-customer-profiles': CACHE4_SAVEN_DAY       
     
      
      
              