server:
  port: ${PORT:7080}

spring:
  application:
    name: edge-gateway
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        
#logging:
#  level:
#    reactor:
#      netty: DEBUG 
#      channel:
#        FluxReceive: DEBUG

                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    