
# ===============================
# = Server Properties
# ===============================
server:
  port: 8181
spring:
  application:
    name: simple-redis-caching
 
redis:
 host: localhost
 port: 8888