
# ===============================
# = Server Properties
# ===============================
server:
  port: 8181

spring:
  application:
    name: spring-security-keycloak-resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.16.8.132:8080/auth/realms/banglalink
     ##     jwk-set-uri: http://172.16.8.132:8080/auth/realms/banglalink/protocol/openid-connect/certs