server:
  port: ${PORT:8081}
  tomcat:
   maxConnections: 1
   acceptCount: 1
   processorCache: 1
   maxKeepAliveRequests: 1
   threads:
     max: 2
     minSpare: 2
spring:
  application:
    name: employee-mcservice-feignclient
    
feign:
  httpclient:
    max-connections-per-route: 150
    max-connections: 100
  client:
    config:
      default:
        connectTimeout: 100
        readTimeout: 1000
        loggerLevel: basic
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7082/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        
        
        





