//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.24 at 12:26:44 PM BDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://imranmadbar.com")
package com.imranmadbar.soap.bindings;
