server:
  port: 9191
  tomcat:
    connection-timeout: 2000
    maxConnections: 2
    acceptCount: 1                      # queued tcp connection up by Tomcat before the server starts rejecting new connections. 
    maxKeepAliveRequests: 2
    threads:
      max: 2
      minSpare: 1                        # minimum number of connections that the connection pool should always have available and ready for use   
spring:
  mvc:
    async:
      request-timeout: 1s
  application:
    name: business-svc
feign:
  httpclient:
    max-connections-per-route: 1
    max-connections: 2
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 5000
        loggerLevel: basic
        
int-url:
  svc1: http://localhost:9999

management:
  endpoints:
    web:
      exposure:
        include: "*"








