//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.26 at 06:13:47 PM BDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://imranmadbar.com/spring-boot-soap-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.imranmadbar.spring_boot_soap_service;
