server:
  port: 8081
spring:
  application:
    name: microservice-one
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:7072/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
        